// Placeholder değerler — sen gerçek rakamları yazacaksın
export const FREE_TIME_ARDIYE: Record<string, number> = {
"marport|hapag" 	    :7,
"mardas|hapag"    	  :7,
"kumport|hapag"      	:8,
"safiport|hapag"   	  :7,
"evyapport|hapag" 	  :8,
"yarimca|hapag"     	:8,
"yilportgebze|hapag"	:7,
"beldeport|hapag"   	:7,
"borusan|hapag"   	  :7,
"rodaport|hapag"   	  :7,
"yilportgemlik|hapag"	:7,
"tceege|hapag"    	  :9,
"socar|hapag"    	    :8,
"nemport|hapag"  	    :6,
"mip|hapag"       	  :6,
"limakport|hapag"   	:7,

"marport|maersk" 	    :8,
"mardas|maersk"    	  :8,
"kumport|maersk"      :8,
"safiport|maersk"   	:10,
"evyapport|maersk" 	  :10,
"yarimca|maersk"     	:10,
"yilportgebze|maersk"	:10,
"beldeport|maersk"   	:10,
"borusan|maersk"   	  :7,
"rodaport|maersk"   	:7,
"yilportgemlik|maersk":7,
"tceege|maersk"    	  :10,
"socar|maersk"    	   :10,
"nemport|maersk"  	   :10,
"mip|maersk"       	  :6,
"limakport|maersk"   	:7,

"marport|cmacgm" 	    :10,
"mardas|cmacgm"    	  :10,
"kumport|cmacgm"      :10,
"safiport|cmacgm"   	:10,
"evyapport|cmacgm" 	  :10,
"yarimca|cmacgm"     	:10,
"yilportgebze|cmacgm"	:10,
"beldeport|cmacgm"   	:10,
"borusan|cmacgm"   	  :10,
"rodaport|cmacgm"   	:10,
"yilportgemlik|cmacgm":10,
"tceege|cmacgm"    	  :10,
"socar|cmacgm"    	  :10,
"nemport|cmacgm"  	  :10,
"mip|cmacgm"       	  :10,
"limakport|cmacgm"   	:10,
};

export const DEFAULT_FREE_TIME_ARDIYE = 5;
