export const PORTS = [
  { id: "marport",       name: "Marport" },
  { id: "mardas",        name: "Mardas" },
  { id: "kumport",       name: "Kumport" },
  { id: "safiport",      name: "Safiport" },
  { id: "evyapport",     name: "Evyapport" },
  { id: "yarimca",       name: "DP World Yarimca" },
  { id: "yilportgebze",  name: "Yilport Gebze" },
  { id: "beldeport",     name: "Beldeport" },
  { id: "borusan",       name: "Borusanport" },
  { id: "rodaport",      name: "Rodaport" },
  { id: "yilportgemlik", name: "Yilport Gemlik" },
  { id: "tceege",        name: "TCE Ege" },
  { id: "socar",         name: "Socar Aliaga" },
  { id: "nemport",       name: "Nemport" },
  { id: "mip",           name: "MIP" },
  { id: "limakport",     name: "Limakport" },
] as const;
